### ISSUE TITLE
Server broken with latest Datahike version

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike-server#53]
I updated the deps for datahike-server, built it and tried to run it with dev-mode. It fails with:

```
2023-03-22 17:09:44.714:INFO::main: Logging initialized @2757ms to org.eclipse.jetty.util.log.StdErrLog
2023-03-22T16:09:44.829Z Zockolette DEBUG [datahike-server.config:33] - Loading config
2023-03-22T16:09:44.842Z Zockolette INFO [datahike-server.config:27] - No config file found at  resources/config.edn
2023-03-22T16:09:44.843Z Zockolette DEBUG [datahike-server.database:9] - Connecting to databases with config:  {:server {:port 3000, :join? false, :loglevel :info, :dev-mode true}, :databases nil}
2023-03-22T16:09:44.856Z Zockolette INFO [datahike-server.database:12] - Creating database...
Exception in thread "main" java.lang.RuntimeException: could not start [#'datahike-server.database/conns] due to
        at mount.core$up$fn__216.invoke(core.cljc:80)
        at mount.core$up.invokeStatic(core.cljc:80)
        at mount.core$up.invoke(core.cljc:78)
        at mount.core$bring.invokeStatic(core.cljc:247)
        at mount.core$bring.invoke(core.cljc:239)
        at mount.core$start.invokeStatic(core.cljc:289)
        at mount.core$start.doInvoke(core.cljc:281)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at datahike_server.core$_main.invokeStatic(core.clj:10)
        at datahike_server.core$_main.doInvoke(core.clj:9)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at datahike_server.core.main(Unknown Source)
Caused by: clojure.lang.ArityException: Wrong number of args (0) passed to: datahike.writer/backend-dispatch
        at clojure.lang.AFn.throwArity(AFn.java:429)
        at clojure.lang.RestFn.invoke(RestFn.java:399)
        at clojure.lang.MultiFn.invoke(MultiFn.java:225)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at datahike.api$create_database.invokeStatic(api.cljc:114)
        at datahike.api$create_database.doInvoke(api.cljc:113)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at datahike_server.database$init_connections.invokeStatic(database.clj:13)
        at datahike_server.database$init_connections.invoke(database.clj:8)
        at datahike_server.database$fn__34091.invokeStatic(database.clj:38)
        at datahike_server.database$fn__34091.invoke(database.clj:37)
        at mount.core$record_BANG_.invokeStatic(core.cljc:74)
        at mount.core$record_BANG_.invoke(core.cljc:73)
        at mount.core$up$fn__216.invoke(core.cljc:81)
        ... 13 more
```

**Comment by TimoKramer** [comment]
@whilo any idea?

**Comment by TimoKramer** [comment]
Closing in favor of https://github.com/replikativ/datahike/issues/621
